// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: persist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PersistedTorrentMeta is the on-disk metadata for an in-flight torrent sync.
// Written once during initNewTorrent, read on startup recovery and during
// finalization (to extract torrent_file bytes for qBittorrent).
//
// This message is a persistence contract, separate from RPC messages in
// qbsync.proto. The two evolve independently.
type PersistedTorrentMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion int32                  `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	TorrentHash   string                 `protobuf:"bytes,2,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PieceSize     int64                  `protobuf:"varint,4,opt,name=piece_size,json=pieceSize,proto3" json:"piece_size,omitempty"`
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	NumPieces     int32                  `protobuf:"varint,6,opt,name=num_pieces,json=numPieces,proto3" json:"num_pieces,omitempty"`
	Files         []*PersistedFileInfo   `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty"`
	TorrentFile   []byte                 `protobuf:"bytes,8,opt,name=torrent_file,json=torrentFile,proto3" json:"torrent_file,omitempty"`
	PieceHashes   []string               `protobuf:"bytes,9,rep,name=piece_hashes,json=pieceHashes,proto3" json:"piece_hashes,omitempty"`
	SaveSubPath   string                 `protobuf:"bytes,10,opt,name=save_sub_path,json=saveSubPath,proto3" json:"save_sub_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistedTorrentMeta) Reset() {
	*x = PersistedTorrentMeta{}
	mi := &file_persist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedTorrentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedTorrentMeta) ProtoMessage() {}

func (x *PersistedTorrentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_persist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedTorrentMeta.ProtoReflect.Descriptor instead.
func (*PersistedTorrentMeta) Descriptor() ([]byte, []int) {
	return file_persist_proto_rawDescGZIP(), []int{0}
}

func (x *PersistedTorrentMeta) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *PersistedTorrentMeta) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *PersistedTorrentMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersistedTorrentMeta) GetPieceSize() int64 {
	if x != nil {
		return x.PieceSize
	}
	return 0
}

func (x *PersistedTorrentMeta) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *PersistedTorrentMeta) GetNumPieces() int32 {
	if x != nil {
		return x.NumPieces
	}
	return 0
}

func (x *PersistedTorrentMeta) GetFiles() []*PersistedFileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *PersistedTorrentMeta) GetTorrentFile() []byte {
	if x != nil {
		return x.TorrentFile
	}
	return nil
}

func (x *PersistedTorrentMeta) GetPieceHashes() []string {
	if x != nil {
		return x.PieceHashes
	}
	return nil
}

func (x *PersistedTorrentMeta) GetSaveSubPath() string {
	if x != nil {
		return x.SaveSubPath
	}
	return ""
}

// PersistedFileInfo is the per-file metadata within a persisted torrent.
// Inode is deliberately omitted — it is a runtime property of the source
// filesystem, only meaningful during the initial InitTorrent handshake.
type PersistedFileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Selected      bool                   `protobuf:"varint,4,opt,name=selected,proto3" json:"selected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersistedFileInfo) Reset() {
	*x = PersistedFileInfo{}
	mi := &file_persist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedFileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedFileInfo) ProtoMessage() {}

func (x *PersistedFileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_persist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedFileInfo.ProtoReflect.Descriptor instead.
func (*PersistedFileInfo) Descriptor() ([]byte, []int) {
	return file_persist_proto_rawDescGZIP(), []int{1}
}

func (x *PersistedFileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PersistedFileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PersistedFileInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PersistedFileInfo) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

var File_persist_proto protoreflect.FileDescriptor

const file_persist_proto_rawDesc = "" +
	"\n" +
	"\rpersist.proto\x12\x06qbsync\"\xec\x02\n" +
	"\x14PersistedTorrentMeta\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12!\n" +
	"\ftorrent_hash\x18\x02 \x01(\tR\vtorrentHash\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"piece_size\x18\x04 \x01(\x03R\tpieceSize\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12\x1d\n" +
	"\n" +
	"num_pieces\x18\x06 \x01(\x05R\tnumPieces\x12/\n" +
	"\x05files\x18\a \x03(\v2\x19.qbsync.PersistedFileInfoR\x05files\x12!\n" +
	"\ftorrent_file\x18\b \x01(\fR\vtorrentFile\x12!\n" +
	"\fpiece_hashes\x18\t \x03(\tR\vpieceHashes\x12\"\n" +
	"\rsave_sub_path\x18\n" +
	" \x01(\tR\vsaveSubPath\"o\n" +
	"\x11PersistedFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1a\n" +
	"\bselected\x18\x04 \x01(\bR\bselectedB Z\x1egithub.com/arsac/qb-sync/protob\x06proto3"

var (
	file_persist_proto_rawDescOnce sync.Once
	file_persist_proto_rawDescData []byte
)

func file_persist_proto_rawDescGZIP() []byte {
	file_persist_proto_rawDescOnce.Do(func() {
		file_persist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_persist_proto_rawDesc), len(file_persist_proto_rawDesc)))
	})
	return file_persist_proto_rawDescData
}

var file_persist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_persist_proto_goTypes = []any{
	(*PersistedTorrentMeta)(nil), // 0: qbsync.PersistedTorrentMeta
	(*PersistedFileInfo)(nil),    // 1: qbsync.PersistedFileInfo
}
var file_persist_proto_depIdxs = []int32{
	1, // 0: qbsync.PersistedTorrentMeta.files:type_name -> qbsync.PersistedFileInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_persist_proto_init() }
func file_persist_proto_init() {
	if File_persist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_persist_proto_rawDesc), len(file_persist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_persist_proto_goTypes,
		DependencyIndexes: file_persist_proto_depIdxs,
		MessageInfos:      file_persist_proto_msgTypes,
	}.Build()
	File_persist_proto = out.File
	file_persist_proto_goTypes = nil
	file_persist_proto_depIdxs = nil
}
