// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: qbsync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QBSyncService_StreamPiecesBidi_FullMethodName = "/qbsync.QBSyncService/StreamPiecesBidi"
	QBSyncService_InitTorrent_FullMethodName      = "/qbsync.QBSyncService/InitTorrent"
	QBSyncService_FinalizeTorrent_FullMethodName  = "/qbsync.QBSyncService/FinalizeTorrent"
	QBSyncService_AbortTorrent_FullMethodName     = "/qbsync.QBSyncService/AbortTorrent"
	QBSyncService_StartTorrent_FullMethodName     = "/qbsync.QBSyncService/StartTorrent"
)

// QBSyncServiceClient is the client API for QBSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QBSyncService handles torrent synchronization between source and destination.
// Destination qBittorrent is the single source of truth for sync status.
// InitTorrent determines what needs syncing by checking qB, active syncs, and filesystem.
type QBSyncServiceClient interface {
	// StreamPiecesBidi provides full-duplex streaming for maximum throughput.
	// Client streams pieces, server streams back acknowledgments as pieces are written.
	// This allows immediate retry on failure without waiting for batch completion.
	StreamPiecesBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WritePieceRequest, PieceAck], error)
	// InitTorrent initializes or resumes a torrent sync.
	// This is the primary entry point - it checks:
	// 1. If torrent is already complete in destination qBittorrent -> COMPLETE
	// 2. If sync is in progress -> returns remaining pieces_needed
	// 3. If files exist on disk -> triggers qB verification, returns verified pieces
	// 4. Fresh torrent -> all pieces needed
	// This RPC is idempotent - safe to call multiple times.
	InitTorrent(ctx context.Context, in *InitTorrentRequest, opts ...grpc.CallOption) (*InitTorrentResponse, error)
	// FinalizeTorrent completes torrent transfer: renames partial files,
	// adds to local qBittorrent, triggers recheck, and waits for verification.
	FinalizeTorrent(ctx context.Context, in *FinalizeTorrentRequest, opts ...grpc.CallOption) (*FinalizeTorrentResponse, error)
	// AbortTorrent aborts an in-progress torrent transfer and cleans up partial files.
	// Called when a torrent is removed from source before streaming completes.
	AbortTorrent(ctx context.Context, in *AbortTorrentRequest, opts ...grpc.CallOption) (*AbortTorrentResponse, error)
	// StartTorrent resumes a stopped torrent on destination qBittorrent.
	// Called by source during disk pressure cleanup after stopping the torrent on source,
	// ensuring destination takes over seeding before source deletes the torrent.
	StartTorrent(ctx context.Context, in *StartTorrentRequest, opts ...grpc.CallOption) (*StartTorrentResponse, error)
}

type qBSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQBSyncServiceClient(cc grpc.ClientConnInterface) QBSyncServiceClient {
	return &qBSyncServiceClient{cc}
}

func (c *qBSyncServiceClient) StreamPiecesBidi(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WritePieceRequest, PieceAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QBSyncService_ServiceDesc.Streams[0], QBSyncService_StreamPiecesBidi_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WritePieceRequest, PieceAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QBSyncService_StreamPiecesBidiClient = grpc.BidiStreamingClient[WritePieceRequest, PieceAck]

func (c *qBSyncServiceClient) InitTorrent(ctx context.Context, in *InitTorrentRequest, opts ...grpc.CallOption) (*InitTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitTorrentResponse)
	err := c.cc.Invoke(ctx, QBSyncService_InitTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qBSyncServiceClient) FinalizeTorrent(ctx context.Context, in *FinalizeTorrentRequest, opts ...grpc.CallOption) (*FinalizeTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeTorrentResponse)
	err := c.cc.Invoke(ctx, QBSyncService_FinalizeTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qBSyncServiceClient) AbortTorrent(ctx context.Context, in *AbortTorrentRequest, opts ...grpc.CallOption) (*AbortTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortTorrentResponse)
	err := c.cc.Invoke(ctx, QBSyncService_AbortTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qBSyncServiceClient) StartTorrent(ctx context.Context, in *StartTorrentRequest, opts ...grpc.CallOption) (*StartTorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTorrentResponse)
	err := c.cc.Invoke(ctx, QBSyncService_StartTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QBSyncServiceServer is the server API for QBSyncService service.
// All implementations must embed UnimplementedQBSyncServiceServer
// for forward compatibility.
//
// QBSyncService handles torrent synchronization between source and destination.
// Destination qBittorrent is the single source of truth for sync status.
// InitTorrent determines what needs syncing by checking qB, active syncs, and filesystem.
type QBSyncServiceServer interface {
	// StreamPiecesBidi provides full-duplex streaming for maximum throughput.
	// Client streams pieces, server streams back acknowledgments as pieces are written.
	// This allows immediate retry on failure without waiting for batch completion.
	StreamPiecesBidi(grpc.BidiStreamingServer[WritePieceRequest, PieceAck]) error
	// InitTorrent initializes or resumes a torrent sync.
	// This is the primary entry point - it checks:
	// 1. If torrent is already complete in destination qBittorrent -> COMPLETE
	// 2. If sync is in progress -> returns remaining pieces_needed
	// 3. If files exist on disk -> triggers qB verification, returns verified pieces
	// 4. Fresh torrent -> all pieces needed
	// This RPC is idempotent - safe to call multiple times.
	InitTorrent(context.Context, *InitTorrentRequest) (*InitTorrentResponse, error)
	// FinalizeTorrent completes torrent transfer: renames partial files,
	// adds to local qBittorrent, triggers recheck, and waits for verification.
	FinalizeTorrent(context.Context, *FinalizeTorrentRequest) (*FinalizeTorrentResponse, error)
	// AbortTorrent aborts an in-progress torrent transfer and cleans up partial files.
	// Called when a torrent is removed from source before streaming completes.
	AbortTorrent(context.Context, *AbortTorrentRequest) (*AbortTorrentResponse, error)
	// StartTorrent resumes a stopped torrent on destination qBittorrent.
	// Called by source during disk pressure cleanup after stopping the torrent on source,
	// ensuring destination takes over seeding before source deletes the torrent.
	StartTorrent(context.Context, *StartTorrentRequest) (*StartTorrentResponse, error)
	mustEmbedUnimplementedQBSyncServiceServer()
}

// UnimplementedQBSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQBSyncServiceServer struct{}

func (UnimplementedQBSyncServiceServer) StreamPiecesBidi(grpc.BidiStreamingServer[WritePieceRequest, PieceAck]) error {
	return status.Error(codes.Unimplemented, "method StreamPiecesBidi not implemented")
}
func (UnimplementedQBSyncServiceServer) InitTorrent(context.Context, *InitTorrentRequest) (*InitTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitTorrent not implemented")
}
func (UnimplementedQBSyncServiceServer) FinalizeTorrent(context.Context, *FinalizeTorrentRequest) (*FinalizeTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeTorrent not implemented")
}
func (UnimplementedQBSyncServiceServer) AbortTorrent(context.Context, *AbortTorrentRequest) (*AbortTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortTorrent not implemented")
}
func (UnimplementedQBSyncServiceServer) StartTorrent(context.Context, *StartTorrentRequest) (*StartTorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTorrent not implemented")
}
func (UnimplementedQBSyncServiceServer) mustEmbedUnimplementedQBSyncServiceServer() {}
func (UnimplementedQBSyncServiceServer) testEmbeddedByValue()                       {}

// UnsafeQBSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QBSyncServiceServer will
// result in compilation errors.
type UnsafeQBSyncServiceServer interface {
	mustEmbedUnimplementedQBSyncServiceServer()
}

func RegisterQBSyncServiceServer(s grpc.ServiceRegistrar, srv QBSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedQBSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QBSyncService_ServiceDesc, srv)
}

func _QBSyncService_StreamPiecesBidi_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QBSyncServiceServer).StreamPiecesBidi(&grpc.GenericServerStream[WritePieceRequest, PieceAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QBSyncService_StreamPiecesBidiServer = grpc.BidiStreamingServer[WritePieceRequest, PieceAck]

func _QBSyncService_InitTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QBSyncServiceServer).InitTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QBSyncService_InitTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QBSyncServiceServer).InitTorrent(ctx, req.(*InitTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QBSyncService_FinalizeTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QBSyncServiceServer).FinalizeTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QBSyncService_FinalizeTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QBSyncServiceServer).FinalizeTorrent(ctx, req.(*FinalizeTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QBSyncService_AbortTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QBSyncServiceServer).AbortTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QBSyncService_AbortTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QBSyncServiceServer).AbortTorrent(ctx, req.(*AbortTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QBSyncService_StartTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QBSyncServiceServer).StartTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QBSyncService_StartTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QBSyncServiceServer).StartTorrent(ctx, req.(*StartTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QBSyncService_ServiceDesc is the grpc.ServiceDesc for QBSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QBSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qbsync.QBSyncService",
	HandlerType: (*QBSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitTorrent",
			Handler:    _QBSyncService_InitTorrent_Handler,
		},
		{
			MethodName: "FinalizeTorrent",
			Handler:    _QBSyncService_FinalizeTorrent_Handler,
		},
		{
			MethodName: "AbortTorrent",
			Handler:    _QBSyncService_AbortTorrent_Handler,
		},
		{
			MethodName: "StartTorrent",
			Handler:    _QBSyncService_StartTorrent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPiecesBidi",
			Handler:       _QBSyncService_StreamPiecesBidi_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "qbsync.proto",
}
