// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: qbsync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PieceErrorCode categorizes piece-level failures for retry decisions.
type PieceErrorCode int32

const (
	PieceErrorCode_PIECE_ERROR_NONE            PieceErrorCode = 0 // Default / unknown (backward-compatible with old cold)
	PieceErrorCode_PIECE_ERROR_IO              PieceErrorCode = 1 // Disk I/O, permission, disk full
	PieceErrorCode_PIECE_ERROR_HASH_MISMATCH   PieceErrorCode = 2 // SHA1 verification failed
	PieceErrorCode_PIECE_ERROR_NOT_INITIALIZED PieceErrorCode = 3 // Torrent not tracked on cold
	PieceErrorCode_PIECE_ERROR_FINALIZING      PieceErrorCode = 4 // Torrent is being finalized
)

// Enum value maps for PieceErrorCode.
var (
	PieceErrorCode_name = map[int32]string{
		0: "PIECE_ERROR_NONE",
		1: "PIECE_ERROR_IO",
		2: "PIECE_ERROR_HASH_MISMATCH",
		3: "PIECE_ERROR_NOT_INITIALIZED",
		4: "PIECE_ERROR_FINALIZING",
	}
	PieceErrorCode_value = map[string]int32{
		"PIECE_ERROR_NONE":            0,
		"PIECE_ERROR_IO":              1,
		"PIECE_ERROR_HASH_MISMATCH":   2,
		"PIECE_ERROR_NOT_INITIALIZED": 3,
		"PIECE_ERROR_FINALIZING":      4,
	}
)

func (x PieceErrorCode) Enum() *PieceErrorCode {
	p := new(PieceErrorCode)
	*p = x
	return p
}

func (x PieceErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PieceErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_qbsync_proto_enumTypes[0].Descriptor()
}

func (PieceErrorCode) Type() protoreflect.EnumType {
	return &file_qbsync_proto_enumTypes[0]
}

func (x PieceErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PieceErrorCode.Descriptor instead.
func (PieceErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{0}
}

// FinalizeErrorCode categorizes finalization failures for retry decisions.
type FinalizeErrorCode int32

const (
	FinalizeErrorCode_FINALIZE_ERROR_NONE       FinalizeErrorCode = 0 // Default / unknown
	FinalizeErrorCode_FINALIZE_ERROR_INCOMPLETE FinalizeErrorCode = 1 // Not all pieces written
)

// Enum value maps for FinalizeErrorCode.
var (
	FinalizeErrorCode_name = map[int32]string{
		0: "FINALIZE_ERROR_NONE",
		1: "FINALIZE_ERROR_INCOMPLETE",
	}
	FinalizeErrorCode_value = map[string]int32{
		"FINALIZE_ERROR_NONE":       0,
		"FINALIZE_ERROR_INCOMPLETE": 1,
	}
)

func (x FinalizeErrorCode) Enum() *FinalizeErrorCode {
	p := new(FinalizeErrorCode)
	*p = x
	return p
}

func (x FinalizeErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalizeErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_qbsync_proto_enumTypes[1].Descriptor()
}

func (FinalizeErrorCode) Type() protoreflect.EnumType {
	return &file_qbsync_proto_enumTypes[1]
}

func (x FinalizeErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalizeErrorCode.Descriptor instead.
func (FinalizeErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{1}
}

// TorrentSyncStatus indicates the current state of a torrent on cold.
type TorrentSyncStatus int32

const (
	// READY: Torrent initialized, stream pieces where pieces_needed[i] is true.
	// If all pieces_needed are false, just call FinalizeTorrent.
	TorrentSyncStatus_SYNC_STATUS_READY TorrentSyncStatus = 0
	// COMPLETE: Torrent already exists in cold qBittorrent and is verified.
	// No action needed - hot can delete this torrent if space is needed.
	TorrentSyncStatus_SYNC_STATUS_COMPLETE TorrentSyncStatus = 1
	// VERIFYING: Files exist on disk, qBittorrent recheck is in progress.
	// Hot should wait and retry InitTorrent after a delay.
	TorrentSyncStatus_SYNC_STATUS_VERIFYING TorrentSyncStatus = 2
)

// Enum value maps for TorrentSyncStatus.
var (
	TorrentSyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_READY",
		1: "SYNC_STATUS_COMPLETE",
		2: "SYNC_STATUS_VERIFYING",
	}
	TorrentSyncStatus_value = map[string]int32{
		"SYNC_STATUS_READY":     0,
		"SYNC_STATUS_COMPLETE":  1,
		"SYNC_STATUS_VERIFYING": 2,
	}
)

func (x TorrentSyncStatus) Enum() *TorrentSyncStatus {
	p := new(TorrentSyncStatus)
	*p = x
	return p
}

func (x TorrentSyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TorrentSyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_qbsync_proto_enumTypes[2].Descriptor()
}

func (TorrentSyncStatus) Type() protoreflect.EnumType {
	return &file_qbsync_proto_enumTypes[2]
}

func (x TorrentSyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TorrentSyncStatus.Descriptor instead.
func (TorrentSyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{2}
}

type WritePieceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentHash   string                 `protobuf:"bytes,1,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	PieceIndex    int32                  `protobuf:"varint,2,opt,name=piece_index,json=pieceIndex,proto3" json:"piece_index,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	PieceHash     string                 `protobuf:"bytes,5,opt,name=piece_hash,json=pieceHash,proto3" json:"piece_hash,omitempty"` // SHA1 hash for verification
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WritePieceRequest) Reset() {
	*x = WritePieceRequest{}
	mi := &file_qbsync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WritePieceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WritePieceRequest) ProtoMessage() {}

func (x *WritePieceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WritePieceRequest.ProtoReflect.Descriptor instead.
func (*WritePieceRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{0}
}

func (x *WritePieceRequest) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *WritePieceRequest) GetPieceIndex() int32 {
	if x != nil {
		return x.PieceIndex
	}
	return 0
}

func (x *WritePieceRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WritePieceRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WritePieceRequest) GetPieceHash() string {
	if x != nil {
		return x.PieceHash
	}
	return ""
}

func (x *WritePieceRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PieceAck is sent by the receiver for each piece in bidirectional streaming.
type PieceAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentHash   string                 `protobuf:"bytes,1,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	PieceIndex    int32                  `protobuf:"varint,2,opt,name=piece_index,json=pieceIndex,proto3" json:"piece_index,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     PieceErrorCode         `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3,enum=qbsync.PieceErrorCode" json:"error_code,omitempty"` // Structured error code for retry decisions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PieceAck) Reset() {
	*x = PieceAck{}
	mi := &file_qbsync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PieceAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PieceAck) ProtoMessage() {}

func (x *PieceAck) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PieceAck.ProtoReflect.Descriptor instead.
func (*PieceAck) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{1}
}

func (x *PieceAck) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *PieceAck) GetPieceIndex() int32 {
	if x != nil {
		return x.PieceIndex
	}
	return 0
}

func (x *PieceAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PieceAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PieceAck) GetErrorCode() PieceErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return PieceErrorCode_PIECE_ERROR_NONE
}

type InitTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentHash   string                 `protobuf:"bytes,1,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PieceSize     int64                  `protobuf:"varint,3,opt,name=piece_size,json=pieceSize,proto3" json:"piece_size,omitempty"`
	TotalSize     int64                  `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	NumPieces     int32                  `protobuf:"varint,5,opt,name=num_pieces,json=numPieces,proto3" json:"num_pieces,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	TorrentFile   []byte                 `protobuf:"bytes,7,opt,name=torrent_file,json=torrentFile,proto3" json:"torrent_file,omitempty"`   // Raw .torrent file for resume state and verification
	PieceHashes   []string               `protobuf:"bytes,8,rep,name=piece_hashes,json=pieceHashes,proto3" json:"piece_hashes,omitempty"`   // SHA1 hashes per piece (hex-encoded)
	SaveSubPath   string                 `protobuf:"bytes,9,opt,name=save_sub_path,json=saveSubPath,proto3" json:"save_sub_path,omitempty"` // Relative sub-path prefix for file storage (e.g., "movies" from category)
	Resync        bool                   `protobuf:"varint,10,opt,name=resync,proto3" json:"resync,omitempty"`                              // Force re-initialization after file selection change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitTorrentRequest) Reset() {
	*x = InitTorrentRequest{}
	mi := &file_qbsync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTorrentRequest) ProtoMessage() {}

func (x *InitTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTorrentRequest.ProtoReflect.Descriptor instead.
func (*InitTorrentRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{2}
}

func (x *InitTorrentRequest) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *InitTorrentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitTorrentRequest) GetPieceSize() int64 {
	if x != nil {
		return x.PieceSize
	}
	return 0
}

func (x *InitTorrentRequest) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *InitTorrentRequest) GetNumPieces() int32 {
	if x != nil {
		return x.NumPieces
	}
	return 0
}

func (x *InitTorrentRequest) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *InitTorrentRequest) GetTorrentFile() []byte {
	if x != nil {
		return x.TorrentFile
	}
	return nil
}

func (x *InitTorrentRequest) GetPieceHashes() []string {
	if x != nil {
		return x.PieceHashes
	}
	return nil
}

func (x *InitTorrentRequest) GetSaveSubPath() string {
	if x != nil {
		return x.SaveSubPath
	}
	return ""
}

func (x *InitTorrentRequest) GetResync() bool {
	if x != nil {
		return x.Resync
	}
	return false
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Inode         uint64                 `protobuf:"varint,4,opt,name=inode,proto3" json:"inode,omitempty"`       // Source filesystem inode for hardlink detection
	Selected      bool                   `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"` // True if file is selected for download (priority > 0)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_qbsync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{3}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileInfo) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FileInfo) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

type InitTorrentResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Status indicates what action hot should take
	Status TorrentSyncStatus `protobuf:"varint,3,opt,name=status,proto3,enum=qbsync.TorrentSyncStatus" json:"status,omitempty"`
	// pieces_needed[i] = true means piece i needs to be streamed.
	// Only populated when status is SYNC_STATUS_READY.
	// Empty if status is SYNC_STATUS_COMPLETE or SYNC_STATUS_VERIFYING.
	PiecesNeeded []bool `protobuf:"varint,4,rep,packed,name=pieces_needed,json=piecesNeeded,proto3" json:"pieces_needed,omitempty"`
	// Hardlink results - which files were hardlinked (for logging/debugging)
	HardlinkResults []*HardlinkResult `protobuf:"bytes,5,rep,name=hardlink_results,json=hardlinkResults,proto3" json:"hardlink_results,omitempty"`
	// Count of pieces that need streaming (convenience field)
	PiecesNeededCount int32 `protobuf:"varint,6,opt,name=pieces_needed_count,json=piecesNeededCount,proto3" json:"pieces_needed_count,omitempty"`
	// Count of pieces already present (hardlinked, verified, or previously received)
	PiecesHaveCount int32 `protobuf:"varint,7,opt,name=pieces_have_count,json=piecesHaveCount,proto3" json:"pieces_have_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitTorrentResponse) Reset() {
	*x = InitTorrentResponse{}
	mi := &file_qbsync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTorrentResponse) ProtoMessage() {}

func (x *InitTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTorrentResponse.ProtoReflect.Descriptor instead.
func (*InitTorrentResponse) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{4}
}

func (x *InitTorrentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitTorrentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InitTorrentResponse) GetStatus() TorrentSyncStatus {
	if x != nil {
		return x.Status
	}
	return TorrentSyncStatus_SYNC_STATUS_READY
}

func (x *InitTorrentResponse) GetPiecesNeeded() []bool {
	if x != nil {
		return x.PiecesNeeded
	}
	return nil
}

func (x *InitTorrentResponse) GetHardlinkResults() []*HardlinkResult {
	if x != nil {
		return x.HardlinkResults
	}
	return nil
}

func (x *InitTorrentResponse) GetPiecesNeededCount() int32 {
	if x != nil {
		return x.PiecesNeededCount
	}
	return 0
}

func (x *InitTorrentResponse) GetPiecesHaveCount() int32 {
	if x != nil {
		return x.PiecesHaveCount
	}
	return 0
}

// HardlinkResult describes the result of hardlink detection for a single file.
type HardlinkResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileIndex     int32                  `protobuf:"varint,1,opt,name=file_index,json=fileIndex,proto3" json:"file_index,omitempty"`       // Index in files array
	Hardlinked    bool                   `protobuf:"varint,2,opt,name=hardlinked,proto3" json:"hardlinked,omitempty"`                      // Whether hardlink was created
	SourcePath    string                 `protobuf:"bytes,3,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`     // Path of existing file used (if hardlinked)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                                 // Error message if hardlink failed
	Pending       bool                   `protobuf:"varint,5,opt,name=pending,proto3" json:"pending,omitempty"`                            // Waiting for another torrent to finish this file
	PreExisting   bool                   `protobuf:"varint,6,opt,name=pre_existing,json=preExisting,proto3" json:"pre_existing,omitempty"` // File already existed on disk with correct size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardlinkResult) Reset() {
	*x = HardlinkResult{}
	mi := &file_qbsync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardlinkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardlinkResult) ProtoMessage() {}

func (x *HardlinkResult) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardlinkResult.ProtoReflect.Descriptor instead.
func (*HardlinkResult) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{5}
}

func (x *HardlinkResult) GetFileIndex() int32 {
	if x != nil {
		return x.FileIndex
	}
	return 0
}

func (x *HardlinkResult) GetHardlinked() bool {
	if x != nil {
		return x.Hardlinked
	}
	return false
}

func (x *HardlinkResult) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *HardlinkResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HardlinkResult) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *HardlinkResult) GetPreExisting() bool {
	if x != nil {
		return x.PreExisting
	}
	return false
}

type CreateHardlinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source file path (relative to base path) that already exists on receiver
	SourcePath string `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	// Target file path (relative to base path) to create as hardlink
	TargetPath    string `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHardlinkRequest) Reset() {
	*x = CreateHardlinkRequest{}
	mi := &file_qbsync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHardlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHardlinkRequest) ProtoMessage() {}

func (x *CreateHardlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHardlinkRequest.ProtoReflect.Descriptor instead.
func (*CreateHardlinkRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{6}
}

func (x *CreateHardlinkRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *CreateHardlinkRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type CreateHardlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHardlinkResponse) Reset() {
	*x = CreateHardlinkResponse{}
	mi := &file_qbsync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHardlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHardlinkResponse) ProtoMessage() {}

func (x *CreateHardlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHardlinkResponse.ProtoReflect.Descriptor instead.
func (*CreateHardlinkResponse) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{7}
}

func (x *CreateHardlinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateHardlinkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFileByInodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inode from the source filesystem (used as unique file identifier)
	Inode         uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileByInodeRequest) Reset() {
	*x = GetFileByInodeRequest{}
	mi := &file_qbsync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileByInodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileByInodeRequest) ProtoMessage() {}

func (x *GetFileByInodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileByInodeRequest.ProtoReflect.Descriptor instead.
func (*GetFileByInodeRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileByInodeRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type GetFileByInodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether a file with this inode has been registered
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Path to the existing file (relative to base path) if found
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileByInodeResponse) Reset() {
	*x = GetFileByInodeResponse{}
	mi := &file_qbsync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileByInodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileByInodeResponse) ProtoMessage() {}

func (x *GetFileByInodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileByInodeResponse.ProtoReflect.Descriptor instead.
func (*GetFileByInodeResponse) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileByInodeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetFileByInodeResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RegisterFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inode from the source filesystem
	Inode uint64 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	// Path where the file was written (relative to base path)
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// File size for verification
	Size          int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFileRequest) Reset() {
	*x = RegisterFileRequest{}
	mi := &file_qbsync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileRequest) ProtoMessage() {}

func (x *RegisterFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileRequest.ProtoReflect.Descriptor instead.
func (*RegisterFileRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterFileRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *RegisterFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type RegisterFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFileResponse) Reset() {
	*x = RegisterFileResponse{}
	mi := &file_qbsync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFileResponse) ProtoMessage() {}

func (x *RegisterFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFileResponse.ProtoReflect.Descriptor instead.
func (*RegisterFileResponse) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FinalizeTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentHash   string                 `protobuf:"bytes,1,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	SavePath      string                 `protobuf:"bytes,2,opt,name=save_path,json=savePath,proto3" json:"save_path,omitempty"`            // Destination path for qBittorrent
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                            // Optional category
	Tags          string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`                                    // Optional tags (comma-separated)
	SaveSubPath   string                 `protobuf:"bytes,5,opt,name=save_sub_path,json=saveSubPath,proto3" json:"save_sub_path,omitempty"` // Relative sub-path prefix for file storage (e.g., "movies" from category)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeTorrentRequest) Reset() {
	*x = FinalizeTorrentRequest{}
	mi := &file_qbsync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeTorrentRequest) ProtoMessage() {}

func (x *FinalizeTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeTorrentRequest.ProtoReflect.Descriptor instead.
func (*FinalizeTorrentRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{12}
}

func (x *FinalizeTorrentRequest) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *FinalizeTorrentRequest) GetSavePath() string {
	if x != nil {
		return x.SavePath
	}
	return ""
}

func (x *FinalizeTorrentRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FinalizeTorrentRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *FinalizeTorrentRequest) GetSaveSubPath() string {
	if x != nil {
		return x.SaveSubPath
	}
	return ""
}

type FinalizeTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                                                         // Final qBittorrent state
	ErrorCode     FinalizeErrorCode      `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=qbsync.FinalizeErrorCode" json:"error_code,omitempty"` // Structured error code for retry decisions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeTorrentResponse) Reset() {
	*x = FinalizeTorrentResponse{}
	mi := &file_qbsync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeTorrentResponse) ProtoMessage() {}

func (x *FinalizeTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeTorrentResponse.ProtoReflect.Descriptor instead.
func (*FinalizeTorrentResponse) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{13}
}

func (x *FinalizeTorrentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinalizeTorrentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FinalizeTorrentResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *FinalizeTorrentResponse) GetErrorCode() FinalizeErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return FinalizeErrorCode_FINALIZE_ERROR_NONE
}

type AbortTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentHash   string                 `protobuf:"bytes,1,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	DeleteFiles   bool                   `protobuf:"varint,2,opt,name=delete_files,json=deleteFiles,proto3" json:"delete_files,omitempty"` // If true, delete partial files; if false, just stop tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTorrentRequest) Reset() {
	*x = AbortTorrentRequest{}
	mi := &file_qbsync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTorrentRequest) ProtoMessage() {}

func (x *AbortTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTorrentRequest.ProtoReflect.Descriptor instead.
func (*AbortTorrentRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{14}
}

func (x *AbortTorrentRequest) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *AbortTorrentRequest) GetDeleteFiles() bool {
	if x != nil {
		return x.DeleteFiles
	}
	return false
}

type AbortTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FilesDeleted  int32                  `protobuf:"varint,3,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"` // Number of partial files deleted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortTorrentResponse) Reset() {
	*x = AbortTorrentResponse{}
	mi := &file_qbsync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTorrentResponse) ProtoMessage() {}

func (x *AbortTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortTorrentResponse.ProtoReflect.Descriptor instead.
func (*AbortTorrentResponse) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{15}
}

func (x *AbortTorrentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AbortTorrentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AbortTorrentResponse) GetFilesDeleted() int32 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

type StartTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentHash   string                 `protobuf:"bytes,1,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"` // Optional tag to apply after starting (e.g., "source-removed")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTorrentRequest) Reset() {
	*x = StartTorrentRequest{}
	mi := &file_qbsync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTorrentRequest) ProtoMessage() {}

func (x *StartTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTorrentRequest.ProtoReflect.Descriptor instead.
func (*StartTorrentRequest) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{16}
}

func (x *StartTorrentRequest) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *StartTorrentRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type StartTorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTorrentResponse) Reset() {
	*x = StartTorrentResponse{}
	mi := &file_qbsync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTorrentResponse) ProtoMessage() {}

func (x *StartTorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTorrentResponse.ProtoReflect.Descriptor instead.
func (*StartTorrentResponse) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{17}
}

func (x *StartTorrentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartTorrentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Piece is a lightweight reference to a piece (no data).
// Used for internal signaling/queueing between hot components.
type Piece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorrentHash   string                 `protobuf:"bytes,1,opt,name=torrent_hash,json=torrentHash,proto3" json:"torrent_hash,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"` // SHA1 hash for verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Piece) Reset() {
	*x = Piece{}
	mi := &file_qbsync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_qbsync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_qbsync_proto_rawDescGZIP(), []int{18}
}

func (x *Piece) GetTorrentHash() string {
	if x != nil {
		return x.TorrentHash
	}
	return ""
}

func (x *Piece) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Piece) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Piece) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Piece) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_qbsync_proto protoreflect.FileDescriptor

const file_qbsync_proto_rawDesc = "" +
	"\n" +
	"\fqbsync.proto\x12\x06qbsync\"\xb6\x01\n" +
	"\x11WritePieceRequest\x12!\n" +
	"\ftorrent_hash\x18\x01 \x01(\tR\vtorrentHash\x12\x1f\n" +
	"\vpiece_index\x18\x02 \x01(\x05R\n" +
	"pieceIndex\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"piece_hash\x18\x05 \x01(\tR\tpieceHash\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\xb5\x01\n" +
	"\bPieceAck\x12!\n" +
	"\ftorrent_hash\x18\x01 \x01(\tR\vtorrentHash\x12\x1f\n" +
	"\vpiece_index\x18\x02 \x01(\x05R\n" +
	"pieceIndex\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x125\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x0e2\x16.qbsync.PieceErrorCodeR\terrorCode\"\xd2\x02\n" +
	"\x12InitTorrentRequest\x12!\n" +
	"\ftorrent_hash\x18\x01 \x01(\tR\vtorrentHash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"piece_size\x18\x03 \x01(\x03R\tpieceSize\x12\x1d\n" +
	"\n" +
	"total_size\x18\x04 \x01(\x03R\ttotalSize\x12\x1d\n" +
	"\n" +
	"num_pieces\x18\x05 \x01(\x05R\tnumPieces\x12&\n" +
	"\x05files\x18\x06 \x03(\v2\x10.qbsync.FileInfoR\x05files\x12!\n" +
	"\ftorrent_file\x18\a \x01(\fR\vtorrentFile\x12!\n" +
	"\fpiece_hashes\x18\b \x03(\tR\vpieceHashes\x12\"\n" +
	"\rsave_sub_path\x18\t \x01(\tR\vsaveSubPath\x12\x16\n" +
	"\x06resync\x18\n" +
	" \x01(\bR\x06resync\"|\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05inode\x18\x04 \x01(\x04R\x05inode\x12\x1a\n" +
	"\bselected\x18\x05 \x01(\bR\bselected\"\xbc\x02\n" +
	"\x13InitTorrentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.qbsync.TorrentSyncStatusR\x06status\x12#\n" +
	"\rpieces_needed\x18\x04 \x03(\bR\fpiecesNeeded\x12A\n" +
	"\x10hardlink_results\x18\x05 \x03(\v2\x16.qbsync.HardlinkResultR\x0fhardlinkResults\x12.\n" +
	"\x13pieces_needed_count\x18\x06 \x01(\x05R\x11piecesNeededCount\x12*\n" +
	"\x11pieces_have_count\x18\a \x01(\x05R\x0fpiecesHaveCount\"\xc3\x01\n" +
	"\x0eHardlinkResult\x12\x1d\n" +
	"\n" +
	"file_index\x18\x01 \x01(\x05R\tfileIndex\x12\x1e\n" +
	"\n" +
	"hardlinked\x18\x02 \x01(\bR\n" +
	"hardlinked\x12\x1f\n" +
	"\vsource_path\x18\x03 \x01(\tR\n" +
	"sourcePath\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x18\n" +
	"\apending\x18\x05 \x01(\bR\apending\x12!\n" +
	"\fpre_existing\x18\x06 \x01(\bR\vpreExisting\"Y\n" +
	"\x15CreateHardlinkRequest\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\"H\n" +
	"\x16CreateHardlinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x15GetFileByInodeRequest\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\"B\n" +
	"\x16GetFileByInodeResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"S\n" +
	"\x13RegisterFileRequest\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"F\n" +
	"\x14RegisterFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xac\x01\n" +
	"\x16FinalizeTorrentRequest\x12!\n" +
	"\ftorrent_hash\x18\x01 \x01(\tR\vtorrentHash\x12\x1b\n" +
	"\tsave_path\x18\x02 \x01(\tR\bsavePath\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\x12\"\n" +
	"\rsave_sub_path\x18\x05 \x01(\tR\vsaveSubPath\"\x99\x01\n" +
	"\x17FinalizeTorrentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x128\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x19.qbsync.FinalizeErrorCodeR\terrorCode\"[\n" +
	"\x13AbortTorrentRequest\x12!\n" +
	"\ftorrent_hash\x18\x01 \x01(\tR\vtorrentHash\x12!\n" +
	"\fdelete_files\x18\x02 \x01(\bR\vdeleteFiles\"k\n" +
	"\x14AbortTorrentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12#\n" +
	"\rfiles_deleted\x18\x03 \x01(\x05R\ffilesDeleted\"J\n" +
	"\x13StartTorrentRequest\x12!\n" +
	"\ftorrent_hash\x18\x01 \x01(\tR\vtorrentHash\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"F\n" +
	"\x14StartTorrentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x80\x01\n" +
	"\x05Piece\x12!\n" +
	"\ftorrent_hash\x18\x01 \x01(\tR\vtorrentHash\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash*\x96\x01\n" +
	"\x0ePieceErrorCode\x12\x14\n" +
	"\x10PIECE_ERROR_NONE\x10\x00\x12\x12\n" +
	"\x0ePIECE_ERROR_IO\x10\x01\x12\x1d\n" +
	"\x19PIECE_ERROR_HASH_MISMATCH\x10\x02\x12\x1f\n" +
	"\x1bPIECE_ERROR_NOT_INITIALIZED\x10\x03\x12\x1a\n" +
	"\x16PIECE_ERROR_FINALIZING\x10\x04*K\n" +
	"\x11FinalizeErrorCode\x12\x17\n" +
	"\x13FINALIZE_ERROR_NONE\x10\x00\x12\x1d\n" +
	"\x19FINALIZE_ERROR_INCOMPLETE\x10\x01*_\n" +
	"\x11TorrentSyncStatus\x12\x15\n" +
	"\x11SYNC_STATUS_READY\x10\x00\x12\x18\n" +
	"\x14SYNC_STATUS_COMPLETE\x10\x01\x12\x19\n" +
	"\x15SYNC_STATUS_VERIFYING\x10\x022\xf3\x04\n" +
	"\rQBSyncService\x12C\n" +
	"\x10StreamPiecesBidi\x12\x19.qbsync.WritePieceRequest\x1a\x10.qbsync.PieceAck(\x010\x01\x12F\n" +
	"\vInitTorrent\x12\x1a.qbsync.InitTorrentRequest\x1a\x1b.qbsync.InitTorrentResponse\x12O\n" +
	"\x0eCreateHardlink\x12\x1d.qbsync.CreateHardlinkRequest\x1a\x1e.qbsync.CreateHardlinkResponse\x12O\n" +
	"\x0eGetFileByInode\x12\x1d.qbsync.GetFileByInodeRequest\x1a\x1e.qbsync.GetFileByInodeResponse\x12I\n" +
	"\fRegisterFile\x12\x1b.qbsync.RegisterFileRequest\x1a\x1c.qbsync.RegisterFileResponse\x12R\n" +
	"\x0fFinalizeTorrent\x12\x1e.qbsync.FinalizeTorrentRequest\x1a\x1f.qbsync.FinalizeTorrentResponse\x12I\n" +
	"\fAbortTorrent\x12\x1b.qbsync.AbortTorrentRequest\x1a\x1c.qbsync.AbortTorrentResponse\x12I\n" +
	"\fStartTorrent\x12\x1b.qbsync.StartTorrentRequest\x1a\x1c.qbsync.StartTorrentResponseB Z\x1egithub.com/arsac/qb-sync/protob\x06proto3"

var (
	file_qbsync_proto_rawDescOnce sync.Once
	file_qbsync_proto_rawDescData []byte
)

func file_qbsync_proto_rawDescGZIP() []byte {
	file_qbsync_proto_rawDescOnce.Do(func() {
		file_qbsync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qbsync_proto_rawDesc), len(file_qbsync_proto_rawDesc)))
	})
	return file_qbsync_proto_rawDescData
}

var file_qbsync_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_qbsync_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_qbsync_proto_goTypes = []any{
	(PieceErrorCode)(0),             // 0: qbsync.PieceErrorCode
	(FinalizeErrorCode)(0),          // 1: qbsync.FinalizeErrorCode
	(TorrentSyncStatus)(0),          // 2: qbsync.TorrentSyncStatus
	(*WritePieceRequest)(nil),       // 3: qbsync.WritePieceRequest
	(*PieceAck)(nil),                // 4: qbsync.PieceAck
	(*InitTorrentRequest)(nil),      // 5: qbsync.InitTorrentRequest
	(*FileInfo)(nil),                // 6: qbsync.FileInfo
	(*InitTorrentResponse)(nil),     // 7: qbsync.InitTorrentResponse
	(*HardlinkResult)(nil),          // 8: qbsync.HardlinkResult
	(*CreateHardlinkRequest)(nil),   // 9: qbsync.CreateHardlinkRequest
	(*CreateHardlinkResponse)(nil),  // 10: qbsync.CreateHardlinkResponse
	(*GetFileByInodeRequest)(nil),   // 11: qbsync.GetFileByInodeRequest
	(*GetFileByInodeResponse)(nil),  // 12: qbsync.GetFileByInodeResponse
	(*RegisterFileRequest)(nil),     // 13: qbsync.RegisterFileRequest
	(*RegisterFileResponse)(nil),    // 14: qbsync.RegisterFileResponse
	(*FinalizeTorrentRequest)(nil),  // 15: qbsync.FinalizeTorrentRequest
	(*FinalizeTorrentResponse)(nil), // 16: qbsync.FinalizeTorrentResponse
	(*AbortTorrentRequest)(nil),     // 17: qbsync.AbortTorrentRequest
	(*AbortTorrentResponse)(nil),    // 18: qbsync.AbortTorrentResponse
	(*StartTorrentRequest)(nil),     // 19: qbsync.StartTorrentRequest
	(*StartTorrentResponse)(nil),    // 20: qbsync.StartTorrentResponse
	(*Piece)(nil),                   // 21: qbsync.Piece
}
var file_qbsync_proto_depIdxs = []int32{
	0,  // 0: qbsync.PieceAck.error_code:type_name -> qbsync.PieceErrorCode
	6,  // 1: qbsync.InitTorrentRequest.files:type_name -> qbsync.FileInfo
	2,  // 2: qbsync.InitTorrentResponse.status:type_name -> qbsync.TorrentSyncStatus
	8,  // 3: qbsync.InitTorrentResponse.hardlink_results:type_name -> qbsync.HardlinkResult
	1,  // 4: qbsync.FinalizeTorrentResponse.error_code:type_name -> qbsync.FinalizeErrorCode
	3,  // 5: qbsync.QBSyncService.StreamPiecesBidi:input_type -> qbsync.WritePieceRequest
	5,  // 6: qbsync.QBSyncService.InitTorrent:input_type -> qbsync.InitTorrentRequest
	9,  // 7: qbsync.QBSyncService.CreateHardlink:input_type -> qbsync.CreateHardlinkRequest
	11, // 8: qbsync.QBSyncService.GetFileByInode:input_type -> qbsync.GetFileByInodeRequest
	13, // 9: qbsync.QBSyncService.RegisterFile:input_type -> qbsync.RegisterFileRequest
	15, // 10: qbsync.QBSyncService.FinalizeTorrent:input_type -> qbsync.FinalizeTorrentRequest
	17, // 11: qbsync.QBSyncService.AbortTorrent:input_type -> qbsync.AbortTorrentRequest
	19, // 12: qbsync.QBSyncService.StartTorrent:input_type -> qbsync.StartTorrentRequest
	4,  // 13: qbsync.QBSyncService.StreamPiecesBidi:output_type -> qbsync.PieceAck
	7,  // 14: qbsync.QBSyncService.InitTorrent:output_type -> qbsync.InitTorrentResponse
	10, // 15: qbsync.QBSyncService.CreateHardlink:output_type -> qbsync.CreateHardlinkResponse
	12, // 16: qbsync.QBSyncService.GetFileByInode:output_type -> qbsync.GetFileByInodeResponse
	14, // 17: qbsync.QBSyncService.RegisterFile:output_type -> qbsync.RegisterFileResponse
	16, // 18: qbsync.QBSyncService.FinalizeTorrent:output_type -> qbsync.FinalizeTorrentResponse
	18, // 19: qbsync.QBSyncService.AbortTorrent:output_type -> qbsync.AbortTorrentResponse
	20, // 20: qbsync.QBSyncService.StartTorrent:output_type -> qbsync.StartTorrentResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_qbsync_proto_init() }
func file_qbsync_proto_init() {
	if File_qbsync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qbsync_proto_rawDesc), len(file_qbsync_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qbsync_proto_goTypes,
		DependencyIndexes: file_qbsync_proto_depIdxs,
		EnumInfos:         file_qbsync_proto_enumTypes,
		MessageInfos:      file_qbsync_proto_msgTypes,
	}.Build()
	File_qbsync_proto = out.File
	file_qbsync_proto_goTypes = nil
	file_qbsync_proto_depIdxs = nil
}
